### ISSUE TITLE
Feature request: Support external state control

### ISSUE THREAD

**Issue by derwaldgeist** [mohithg/react-switchery#14]
React Switchery works fine, if it has full control over its internal state.

However, if you try to use it as a "controlled" input (by modifying its checked prop over time, e.g. in a Redux setup), it does not work as expected. It keeps its own internal state, no matter of changes of the checked prop. This makes it pretty much unusable in these cases.

**Comment by andylacko** [comment]
this one got me, did't expected such behaviour, hmm, I need to wait or change lib

or fix it

**Comment by mohithg** [comment]
Done in 1.2.1 please confirm.

**Comment by nasospsa** [comment]
This doesn't seem fixed.

**Comment by anderfsilva** [comment]
This is not fixed. Version: 1.2.3

I had to control the component visibility to set initial state with hooks.

`{status && (<Switch />)}`
